### ISSUE TITLE
Nuget Update

### ISSUE THREAD

**Issue by Wolftousen** [toddams/RazorLight#235]
**Is your feature request related to a problem? Please describe.**
NuGet hasn't been updated since Nov 2nd 2017. I know this due to changes to DefaultMetadataReferenceManager.cs that fix a null reference when using a specific assembly is not fixed in the version in NuGet.

**Describe the solution you'd like**
Any chance we can update NuGet to beta2 or something?

**Comment by michielpeeters** [comment]
I'll be happy to create a new nuget package based on the master branch, the only problem is that the owner @toddams is the one that should upload it. When this is updated FluentEmail can also be updated accordingly with the new version because it now crashes on .net472 projects.

**Comment by Wolftousen** [comment]
I'll likely just make a fork off of the version Nuget currently has.

I've found a good number of changes that I don't agree with or break what we were doing.

1. Now you are forced to have a "project" of either embedded resource, file, or custom instead of having a reasonable default.
2. The template caching was "hidden", so now you just call CompileTemplateAsync every time and then have no idea if that key was or wasn't previously compiled unless you keep track of it yourself.

I'm sure I'll find other things if I keep going, but these two issues boggle my mind considering they break backwords compatibility and put new expectations on devs without new/updated/reasonable documentation that these things have changed or how to properly execute on them.

**Comment by michielpeeters** [comment]
I agree with point one, which is just weird. I needed to bypass some stuff to make RazorLight with FluentEmail to work. I don't fully agree with your second point. Do you really want to have control with the cache? I guess you want to provide some timelimits etc. (configuration settings) but if it has been stored or not, that shouldn't bother though?

Still, it is good to hear that you are going to create a fork from it :-) I guess that's the author wants as well because he has trouble in his personal life (I read it somewhere). If this is working FluentEmail can grab your package instead of this one :-).

**Comment by Wolftousen** [comment]
It's not that i want to manipulate the cache, I want to know whether something has been cached or not.  You used to be able to do this with RazorLightEngine.TemplateCache.RetrieveTemplate, but for some reason that was removed and combined into CompileTemplate.  In my mind that confuses the purpose of CompileTemplate b/c know you don't know if you are getting a cache object back or a brand new one.

I can understand taking away access directly to TemplateCache, but why not make a RetrieveTemplate function on the RazorLightEngine object that exposes the cache lookup function...

In any case, i've started my fork privately for now.
