### ISSUE TITLE
Null Reference in RoslynCompilationService.CompileAndEmit only while running on Linux

### ISSUE THREAD

**Issue by kush-c** [toddams/RazorLight#269]
**Describe the bug**
Razorlight worked fine while developing on our Windows machines, but throws a NullReferenceException when we deployed to our fleet running in linux. 

Exception Trace I'm able to retrieve from logs:
`Object reference not set to an instance of an object.
at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(IGeneratedRazorTemplate razorTemplate)
at RazorLight.Compilation.RoslynCompilationService.CompileAsync(IGeneratedRazorTemplate razorTemplate)
--- End of stack trace from previous location where exception was thrown ---
at RazorLight.Compilation.TemplateFactoryProvider.CompileAsync(IGeneratedRazorTemplate razorTemplate)
at RazorLight.Compilation.TemplateFactoryProvider.CreateFactoryAsync(String templateKey)
at RazorLight.RazorLightEngine.CompileTemplateAsync(String key)
at RazorLight.RazorLightEngine.CompileRenderAsync(String key, Object model, Type modelType, ExpandoObject viewBag)`

**To Reproduce**
call _engine.CompileRenderAsync(...)

**Expected behavior**
The call should succeed just like in windows.

**Information (please complete the following information):**
 - OS: Ubuntu 16.04
 - Platform : project .net core 2.1
 - RazorLight version  2.0.0-beta1
 - Visual Studio version Visual Studio Community 15.9.8

**Comment by weyert** [comment]
I have the opposite issue working fine in Docker+Linux but fails to work when deployed to a Windows Server :( Did you ever found the solution for this?

**Comment by kush-c** [comment]
No we didn't, but .Netcore has some native methods we used and ended up
bypassing Razorlite altogether.

**Comment by KeterSCP** [comment]
In my case, the issue was caused by using immutable types anywhere in the template. Any access to immutable type from `System.Collections.Immutable` directly in template caused the same exception. Workflow on project was following:
- Deploy project to build server (Debian)
- Run tests on the build server
- Build docker image
- Deploy docker images to the production server

And if we built docker image on the windows machine everything worked fine.

After removing parts from template one by one I discovered lines that caused the problem, and at every line, there was some immutable type access (like `ImmutableList`, `ImmutableDictionary`, etc). After replacing these types with simple ones from `System.Collections.Generic` issue disappeared.
