### ISSUE TITLE
Support for .NET core 3.1

### ISSUE THREAD

**Issue by rajasekarshanmugam** [toddams/RazorLight#302]
At the moment, razor light seems to support with libraries binding to .NET core 3.0. With 3.1 already out and on LTS, is it possible to support compiling against it?

csproj for razor light indicates support till netcoreapp3.0. We might need to support netcoreapp3.1 and also changes related references to 3.1

Tried generating a PR with a branch, but was not allowed due to permissions. Is there anything more that is required?

**Comment by jzabroski** [comment]
@rajasekarshanmugam To create a PR, first click the Fork button in the top right of the github.com/toddams/RazorLight page.

Then, you will have a copy of the repo at github.com/rajasekarshanmugam/RazorLight - note that while GitHub makes it easy to fork via GUI, you have to pretty much use the command line to keep up to date, as your "remote" GitHub repo will be your fork, not our fork, so to pull down updates from our repo, you'll need to fetch them into your repo and merge them.  I find its better to do a fetch + merge as separate steps so that you can see what's changed and then apply those changes.  GitHub also has tutorials on how to do these steps.

Once you've pushed your changes to a branch on your repo, you create Create PR from your branch to this branch.  There's no special permissions required, because all you're doing is dropping code in our mailbox, and we can choose whether to accept or reject it.

![image](https://user-images.githubusercontent.com/447485/71181593-75eeed80-2242-11ea-9db5-c8a17487e4d7.png)

**Comment by jzabroski** [comment]
@rajasekarshanmugam I just did this, so you dont have to.
