### ISSUE TITLE
missing Antlr3.Runtime, Version=3.1.3.22795, Culture=neutral, PublicKeyToken=null

### ISSUE THREAD

**Issue by pomarc** [toddams/RazorLight#323]
when running my WPF, .NET Framework 4.7.2 application,  the call to
```
  string result = engine.CompileRenderStringAsync(Guid.NewGuid().ToString(), 
                template.Content,
                Model
            ).Result;
```

throws 
`FileLoadException, can't load 'Antlr3.Runtime, Version=3.1.3.22795, Culture=neutral, PublicKeyToken=null or one of its deps.`
  

the above code is on a .net standard 2.0 class library, referenced by the main application.
the class library works fine when called from an xUnit unit test.
the version of razorlight is   2.0.0-beta4

explicitly calling Install-Package Antlr.Runtime -Version=3.1.3.22795 succeeds in the class library but fails on the app.
installing the latest antlr.runtime on the app succeeds but the crash still remains.

**Comment by jzabroski** [comment]
Did you use the PreserveCompilationContext settings ?  What version of msbuild/dotnet are you using to build/pack your net472 app?  Are you using csproj legacy format or csproj SDK format?

**Comment by jzabroski** [comment]
https://github.com/toddams/RazorLight#im-getting-cannot-find-reference-assembly-microsoftaspnetcoreantiforgerydll-exception-on-net-core-app-30-or-higher

**Comment by pomarc** [comment]
> Did you use the PreserveCompilationContext settings ? 
yep, to no avail.

> What version of msbuild/dotnet are you using to build/pack your net472 app? 
I use vs 2019, msbuild 16.4.0.56107

> Are you using csproj legacy format or csproj SDK format?
legacy, <Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

**Comment by jzabroski** [comment]
Please use modern project file format and let me know if that fixes things.  If you're not using PackageReference syntax, you cant generate a .deps.json and can't tell the .NET runtime how to interpret all your dependencies.  While I'm sure you can get this to work by manually loading the right assemblies, it seems like a lot of dirty work vs just moving to the new project file format.  

If you haven't moved yet and the reason is due to wanting to host this in a strange context, let's discuss.
