### ISSUE TITLE
Strong Name RazorLight

### ISSUE THREAD

**Issue by geisi93** [toddams/RazorLight#343]
Would it be possible to Strong Name Sign the RazorLight.dll (2.0.0-beta7)? This would enable Strong Named Projects to use RazorLight without the need of using any hacky Strong Namer.

Thanks in Advance.

**Comment by jzabroski** [comment]
@geisi93 I'll close this request.  Please re-open when you have time to answer my questions.  Thanks.

**Comment by doxxx** [comment]
The issue with StrongNamer is that now I also have to use it in every application that uses my (strong-named) library that depends on RazorLight, otherwise I get runtime errors when compiling templates:

> The type 'TemplatePage<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'RazorLight, Version=2.3.0.0, Culture=neutral, PublicKeyToken=e33b67d3bb5581e4'.

Microsoft's guidance on this issue: https://github.com/dotnet/runtime/blob/main/docs/project/strong-name-signing.md

> Because of the viral nature of strong-naming, it is recommended that publicly published .NET libraries are strong-named. Not strong-naming a .NET library excludes anyone who does need to strong-name their application or library from using it.

**Comment by doxxx** [comment]
That said, perhaps I should disabling strong-naming for my assemblies since apparently it's no longer really recommended for .NET 5+ applications.
