### ISSUE TITLE
Model value in layout page

### ISSUE THREAD

**Issue by kae** [toddams/RazorLight#4]
It looks like that model object passed to Parse method cannot be accessed in layout page.

Is it intentional or I missing something?

**Comment by toddams** [comment]
Since layout can be used multiple templates, and all these templates may have different types of model - which model type shoud be set on Layout? I imagine that it is possible to use *dynamic* as a Layout model and on the process of rendering pass model from the template to the layout and hope that there won't be any name mismatches / conflicts, etc.

But, there is already a possibility to use ViewBag object inside the core, but API is not ready yet. I will put this on backlog, so when it is ready you could use it like this

````CSharp
//create a model for the template
var model = new MyModel()
{
    Title = "Test"
};

//create a dynamic viewbag
dynamic viewBag = new ExpandoObject();
viewBag.DataForLayoutPage = "Hello world";

string result = engine.Parse("key", model, viewBag);
````

Viewbag is accessible both from template page and it's layout, so it might solve your problem, if you want to pass some data to it

**Comment by kae** [comment]
That would be nice, thanks.

Is there any expectation about timeframe of such changes?

On a side note, this "model sharing" is available at least in https://www.nuget.org/packages/RazorEngine/ (I'm in the migration path from it for .NET Core). I'm not really shure was it some extension to standard behavior or is it also available in default MVC

**Comment by toddams** [comment]
I think 1-2 days - and it will be ready

**Comment by kae** [comment]
Will wait in anticipation! :+1:

**Comment by toddams** [comment]
Here we go 08ccd0d

beta2 version in already on [Nuget](https://www.nuget.org/packages/RazorLight/)
