### ISSUE TITLE
EngineFactory for ParseString

### ISSUE THREAD

**Issue by senj** [toddams/RazorLight#50]
You have this example 

```
string content = "Hello @Model.Name. Welcome to @Model.Title repository";

var model = new
{
  Name = "John Doe",
  Title = "RazorLight"
};

string result = engine.ParseString(content, model); //Output: Hello John Doe, Welcome to RazorLight repository
```

Where do I get the engine object from, because there is no constructor CreateString() or sth.

**Comment by toddams** [comment]
We create just typical Physical factory and pass there a dummy value, like "C:/".       ¯\_(ツ)_/¯

**Comment by senj** [comment]
Ok this would have been my idea too.
Is it possible to use ParseString with dynamic somehow?
Because with the extension method dynamic is not allowed by the compiler

```
var result = engine.ParseString<dynamic>(template, model);
```

**Comment by toddams** [comment]
Use extension method as a static method call:

````CSharp
dynamic model = new ExpandoObject();
ParsingExtensions.ParseString(engine, template, model);
````

**Comment by senj** [comment]
ah great thank you

**Comment by grokky1** [comment]
The dummy `c:\` path trick works, but it is a hack. Also it assumes a Windows system.

It should be possible to create an engine without relying on the filesystem. For example, in many cases we want to parse a template loaded from the database. (so no filesystem should be assumed)

Until then, a better way is to do this:

    var engine = RazorLight.EngineFactory.CreatePhysical(Path.DirectorySeparatorChar.ToString())

That is safer for use, because it works on all platforms.

**Comment by toddams** [comment]
You are absolutely right, and this behavior will be changed in 2.0

**Comment by grokky1** [comment]
@toddams YEAH! I can't wait for the new version, I have a feeling it will be awesome. 😄
