### ISSUE TITLE
RazorLight not working on Amazon Lambda

### ISSUE THREAD

**Issue by shenhaijun** [toddams/RazorLight#75]
Got the following error when using RazorLight (1.0.0-rc2) on AWS lambda. Can not use the latest version since AWS lambda only support .Net Core 1.0.

"Value cannot be null.
Parameter name: assembly: ArgumentNullException
at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)"

The same code works perfectly well when running in a dotnet core console app.

**Comment by toddams** [comment]
I can not be responsible for the environment you are using, as well as I'm completely unaware about how AWS lambda provides .NET execution environment. 

I would like to help you, but unfortunately you are using old version of RazorLight (because of reasons) and it's unsupported, has bugs and other stuff that may cause the exception you described, so there's nothing I can do in this situation

**Comment by gsaadeh** [comment]
This is still an issue with .NET Core 2.1 and Lambda, getting this error:

```The type or namespace name 'Razor' does not exist in the namespace 'RazorLight' (are you missing an assembly reference?)```
