### ISSUE TITLE
A lot of types missing - Failed to compile generated Razor template

### ISSUE THREAD

**Issue by alexzaytsev-newsroomly** [toddams/RazorLight#92]
When i try to compile a razor view to string from embedded resource using `netcoreapp2.0` i get a bunch of exceptions:

```
RazorLight.TemplateCompilationException: 'Failed to compile generated Razor template:
- (3:29) The type or namespace name 'Razor' does not exist in the namespace 'RazorLight' (are you missing an assembly reference?)
- (3:63) Predefined type 'System.String' is not defined or imported
- (3:83) Predefined type 'System.Type' is not defined or imported
- (7:10) The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
- (8:10) The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
- (9:10) The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
- (10:10) The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
- (11:56) The type or namespace name 'TemplatePage<>' does not exist in the namespace 'RazorLight' (are you missing an assembly reference?)
- (11:69) The type or namespace name 'RedisTester' could not be found (are you missing a using directive or an assembly reference?)
- (14:66) The return type of an async method must be void, Task or Task<T>
- (14:38) The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?)
- (14:66) 'GeneratedTemplate.ExecuteAsync()': no suitable method found to override
- (16:12) Predefined type 'System.Object' is not defined or imported
- (16:12) The name 'BeginContext' does not exist in the current context
- (16:25) Predefined type 'System.Int32' is not defined or imported
- (16:29) Predefined type 'System.Int32' is not defined or imported
- (16:34) Predefined type 'System.Boolean' is not defined or imported
- (17:12) Predefined type 'System.Object' is not defined or imported
- (17:12) The name 'WriteLiteral' does not exist in the current context
- (17:25) Predefined type 'System.String' is not defined or imported
- (18:12) Predefined type 'System.Object' is not defined or imported
- (18:12) The name 'EndContext' does not exist in the current context
- (19:12) Predefined type 'System.Object' is not defined or imported
- (19:12) The name 'BeginContext' does not exist in the current context
- (19:25) Predefined type 'System.Int32' is not defined or imported
- (19:30) Predefined type 'System.Int32' is not defined or imported
- (19:34) Predefined type 'System.Boolean' is not defined or imported
- (9:0) Predefined type 'System.Object' is not defined or imported
- (9:0) The name 'Write' does not exist in the current context
- (9:6) Predefined type 'System.Object' is not defined or imported
- (9:6) The name 'Model' does not exist in the current context
- (25:12) Predefined type 'System.Object' is not defined or imported
- (25:12) The name 'EndContext' does not exist in the current context
- (26:12) Predefined type 'System.Object' is not defined or imported
- (26:12) The name 'BeginContext' does not exist in the current context
- (26:25) Predefined type 'System.Int32' is not defined or imported
- (26:30) Predefined type 'System.Int32' is not defined or imported
- (26:34) Predefined type 'System.Boolean' is not defined or imported
- (27:12) Predefined type 'System.Object' is not defined or imported
- (27:12) The name 'WriteLiteral' does not exist in the current context
- (27:25) Predefined type 'System.String' is not defined or imported
- (28:12) Predefined type 'System.Object' is not defined or imported
- (28:12) The name 'EndContext' does not exist in the current context
- (14:66) 'GeneratedTemplate.ExecuteAsync()': not all code paths return a value

See CompilationErrors for detailed information
'
```

My code is:

```
class Program
{
static void Main(string[] args)
{
var engine = new EngineFactory().ForEmbeddedResources(typeof(Program));
 var s = engine.CompileRenderAsync("Views.Rz.cshtml", new RzModel {Name = "shoes"}).GetAwaiter().GetResult();
}

}
```

My model:

```
public class RzModel
    {
        public string Name { get; set; }
    }
```

My template:
```
@model MyAssembly.RzModel
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    @Model.Name
</body>
</html>
```

**Comment by bolanki** [comment]
I am having the same issues...

`  public class Program
  {
    static void Main(string[] args)
    {
      IRazorLightEngine engine = new EngineFactory().Create(new EmbeddedRazorProject(typeof(Program)));

      const string templateKey = "this_is_my_key";
      var result = engine.CompileRenderAsync(templateKey, "Hello @Model.Name", new { Name = "Jeff" }).Result;

      Console.WriteLine($"Parsing result = {result}");
      Console.WriteLine($"Cache contains key '{templateKey}' : {engine.TemplateCache.Contains(templateKey)}");
      Console.WriteLine("Press any key to exit...");
      Console.ReadKey();
    }
  }`

> System.AggregateException: 'One or more errors occurred. (Failed to compile generated Razor template:
- (3:29) The type or namespace name 'Razor' does not exist in the namespace 'RazorLight' (are you missing an assembly reference?)
- (3:63) Predefined type 'System.String' is not defined or imported
- (3:82) Predefined type 'System.Type' is not defined or imported
- (7:10) The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
- (8:10) The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
- (9:10) The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
- (10:10) The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
- (11:56) The type or namespace name 'TemplatePage<>' does not exist in the namespace 'RazorLight' (are you missing an assembly reference?)
- (11:69) Cannot define a class or member that utilizes 'dynamic' because the compiler required type 'System.Runtime.CompilerServices.DynamicAttribute' cannot be found. Are you missing a reference?
- (11:69) Predefined type 'System.Boolean' is not defined or imported
- (14:66) The return type of an async method must be void, Task or Task<T>
- (14:38) The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?)
- (14:66) 'GeneratedTemplate.ExecuteAsync()': no suitable method found to override
- (16:12) Predefined type 'System.Object' is not defined or imported
- (16:12) The name 'BeginContext' does not exist in the current context
- (16:25) Predefined type 'System.Int32' is not defined or imported
- (16:28) Predefined type 'System.Int32' is not defined or imported
- (16:31) Predefined type 'System.Boolean' is not defined or imported
- (17:12) Predefined type 'System.Object' is not defined or imported
- (17:12) The name 'WriteLiteral' does not exist in the current context
- (17:25) Predefined type 'System.String' is not defined or imported
- (18:12) Predefined type 'System.Object' is not defined or imported
- (18:12) The name 'EndContext' does not exist in the current context
- (19:12) Predefined type 'System.Object' is not defined or imported
- (19:12) The name 'BeginContext' does not exist in the current context
- (19:25) Predefined type 'System.Int32' is not defined or imported
- (19:28) Predefined type 'System.Int32' is not defined or imported
- (19:32) Predefined type 'System.Boolean' is not defined or imported
- (0:1) Predefined type 'System.Object' is not defined or imported
- (0:1) The name 'Write' does not exist in the current context
- (0:7) Predefined type 'System.Object' is not defined or imported
- (0:7) The name 'Model' does not exist in the current context
- (25:12) Predefined type 'System.Object' is not defined or imported
- (25:12) The name 'EndContext' does not exist in the current context
- (14:66) 'GeneratedTemplate.ExecuteAsync()': not all code paths return a value

See CompilationErrors for detailed information
)'

**Comment by toddams** [comment]
Set preserveCompilationContext to true in your csproj. Then clean and rebuild the project

**Comment by bolanki** [comment]
Whoo hoo!!! Finally... thank you!!! The PreserveCompilationContext attribute did it for me :)

**Comment by alexzaytsev-newsroomly** [comment]
Thanks @toddams. Perhaps the doco can be updated with this info?

**Comment by toddams** [comment]
Yep, new readme is already there

**Comment by alexzaytsev-newsroomly** [comment]
@toddams the readme only specified that the `preservecompilationcontext` is a fix for `Can't load metadata reference from the entry assembly` which is not the exception myself and @bolanki were getting. perhaps this can be extended also?

**Comment by toddams** [comment]
I would kindly request not to open issues about missing stuff at documentation. We are in alpha and documentation is kinda out of date and will be updated with further releases
